export const ADD_ERROR ="ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SETCURRENT_USER = "SETCURRENT_USER;"
export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const REMOVE_MESSAGES = "REMOVE_MESSAGES";
